### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by gw15simpsondavid1** [gw15simpsondavid1/slhs-handbook#1]
- [ ] Page 6: Respect, dignity & everyone achieving their potential - Link to doc, update link to doc, get link
- [ ] Page 7: Visions, values and aims - Update VVA, link to film, get film
- [ ] Page 14: The school year - Update for session 2018/19, get updated data
- [ ] Page 14: School role, update, get data
- [ ] Page 15: Free school meals and clothing grants, link to ERC page online, get link
- [ ] Page 34: Enrolment, links to info on ERC website, get links
- [ ] Page 35: School admission arrangements, update link, get link
- [ ] Page 43, School meals, Payment4Schools = Parent Pay ? Link, get link
- [ ] Page 44, Clubs & Activities, Celebrating Achievement link to school website, get link
- [ ] Page 46, Parental Involvement, link to school website, get link
- [ ] Page 48, Parent Council, Update, get data
